Update various button state colours
peeldao/juicecrowd pull request #211
Opened 2023-11-16 05:11 UTC by johnnyd-eth

- Update some of the `blue-bs`s which were slightly off from the latest designs (https://www.figma.com/file/tKUGbpnRRRNPqf4qpmsprZ/Juicecrowd-%E2%80%93-Landing-Page?node-id=638%3A32248&mode=dev)
- Create various knew shadcn classes and implement across the button component according to designs

2023-11-17 05:31 UTC, wraeth-eth commented on tailwind.config.ts
> +          50: '#E5EBFF',
are the bluebs not up to date with figma? I ripped this from JB

2023-11-21 20:44 UTC, wraeth-eth requested changes
@johnnyd-eth The destructive and outline-primary are missing disabled states

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/pinTSPPZHK80UCzWAYgo/a8bab7b0-8f0d-4c89-a98e-9844a5b8bd1a.png)

2023-11-22 08:29 UTC, johnnyd-eth commented
@wraeth-eth Good catch sir, I've patched 🖖

2023-11-26 22:44 UTC, wraeth-eth approved these changes

2023-11-26 22:45 UTC, merged